# Generated by Django 2.2.10 on 2020-03-28 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupation',
                'db_table': 'Occupation',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('sexo', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('isWhatsapp', models.BooleanField(default=False, verbose_name='Is whatsapp')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('landline', models.CharField(blank=True, max_length=15, null=True, verbose_name='landline')),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaborator.Occupation', verbose_name='occupation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
                'db_table': 'Profile',
            },
        ),
    ]
