BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
        BBBBBBBBBB
       
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXXX
    XXXXXXX
BBBBBBBB