# Generated by Django 2.2.10 on 2020-03-28 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborator', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('skip', models.BooleanField(default=False, verbose_name='Skip')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price of appointment')),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'typeAppointment',
                'verbose_name_plural': 'typeAppointment',
                'db_table': 'typeAppointment',
            },
        ),
        migrations.CreateModel(
            name='NotificationPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('appointment-saved', 'Notify to pacientes appointments')], max_length=200, verbose_name='Action')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Notification Support Team',
                'verbose_name_plural': 'Notification Support Team',
                'db_table': 'NotificationSupportTeam',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60, null=True, verbose_name='Appointment name')),
                ('date_appointment', models.DateTimeField(verbose_name='date of appointment')),
                ('consulting', models.BooleanField(default=False, verbose_name='Consulting')),
                ('isCanceled', models.BooleanField(default=False, editable=False)),
                ('calendarUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('calendarOwnerTID', models.IntegerField(default=2019700909, editable=False)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.Patient', verbose_name='Patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collaborator.Profile', verbose_name='Professional')),
                ('type_appointment', models.ManyToManyField(to='appointment.TypeAppointment', verbose_name='Type appointment')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointment',
                'db_table': 'appointment',
            },
        ),
    ]
