# Generated by Django 2.2.10 on 2020-04-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20200404_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='calendarOwnerTID',
            field=models.IntegerField(default=1110078537, editable=False),
        ),
    ]
