# Generated by Django 2.2.10 on 2020-03-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=24803911, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
