# Generated by Django 2.2.10 on 2020-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200328_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=17338171, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
