# Generated by Django 2.2.10 on 2020-04-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200401_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=16236192, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
