# Generated by Django 2.2.10 on 2020-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200404_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=5809307, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
