# Generated by Django 2.2.10 on 2020-04-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20200404_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=8049832, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
